version: 0.2
env:
  secrets-manager:
    TOKEN: prod/sonar:sonarToken
    HOST: prod/sonar:Host
    Organization: prod/sonar:Organization
    Project: prod/sonar:nci-forum-ui

phases:
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:/sonar-scanner-5.0.1.3006-linux/bin/
  build:
    commands:
    - sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.login=$TOKEN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
    - curl -u $TOKEN https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
    - cat result.json
    - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then $CODEBUILD_BUILD_SUCCEEDING -eq 0; fi
